version: '2'
services:
  gtw-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/gtw/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gtw
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
